name: 'ScriptLattes action'
description: 'Executa ScriptLattes em GitHub Actions'
inputs:
  config-file-path: 
    description: 'Caminho para o arquivo de configuração de execução do ScriptLattes'
    required: true
  output-directory-path:
    description: 'Caminho para o qual o diretório de saída do ScriptLattes será copiado'
    required: false
    default: /github/workspace/scriptlattes/output
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BASE_IMAGE: ${{ inputs.scriptlattes-base-image }}
  args:
    - ${{ inputs.config-file-path }}
    - ${{ inputs.output-directory-path }}